#!/bin/sh
# May at somepoint want to do this `date +%Y%m%d%H%M%S` for a version
#usage() {
#	echo "usage: bump-version <version-id>"
#}
#
#if [ $# -ne 1 ]; then
#	usage
#	exit 1
#fi

echo cports-0.$(date +%Y%m%d) > VERSION

git add VERSION

./scripts/git2cl > ChangeLog
git add ChangeLog

git commit -m "Bumped version number to $(cat VERSION)"
