#+TITLE: cports - TCHPC fork

* Why fork cports
 - Needed more than just one version of gcc, intel, pgi builds of
   software
 - Needed more control with being able to add packages
 - Needed more variables put into the modulefiles
 - Needed repeatable and documented methods of installing libraries
   and applications
 - Didn't care too much about generating portable objects, and since
   it's dervived from a derived piece of work it just makes life
   easier.
 - Why not use Gentoo, NetBSD ports, packaging system XYZ?
   - most of the other systems are not as easily hackable as just
     makefiles
   - don't allow multiple verisons of software installed
* The upstream authors
  - mpkg - http://staff.e.kth.se/mpkg/index.html
  - cports - http://www.caoslinux.org/
* The current authors
 - Mainly staff from TCHPC
   - The time is paid for by eINIS, HPCE2, OIP and maybe one or two
     other projects that may be benefitting from the results of this
     build/package system.
* What cports doesn't do 
 - It doesn't generate portable binaries
 - Provide good documentation on the modifications TCHPC has made
 - Support for people who use is :)
 - Dependancy and conflict checking of the packages, the admin who is
   writing the package will need to do this
 - Work with non-gnu based tools (it's a fork and the original authors
   used and based everything on gnu make etc...)
* Requirements
** Required software
 - gnu make
 - gcc (and basic devel, compile tools etc...)
 - wget
 - environment-modules

you can do a "make check-environment" to see if you meet the basic
requirements.
* Installation and configuration
  - Unpack cports-?.tar.bz2 to somewhere
  - Configure cports by creating either /etc/mpkg.mk or
    ${HOME}/.mpkg.mk see the example in doc/examples/dot.mpkg.mk
  - Configure environment modules either at the system level or in
    your own home directory in ${HOME}/privatemodules/cports see
    doc/examples/privatemodules.cports make sure the paths in here
    correspond to the MODULEDIR variable in /etc/mpkg.mk or
    ${HOME}.mpkg.mk. Look in cports/mk/gnu.def.mk for some default
    options that you can override and or set.
  - cd into *cports/packages/bootstrap/1.0* and type make install,
    this will try and install the basic packages needed to build the
    rest of the system
** proxies
   - many people have a http_proxy variable set in their shell config.
     However make installs often fail on ftp download attempts. So you
     should set an ftp_proxy variable as well.  For example,
     ftp_proxy=http://proxy.yourdomain.ie:80.  This works in our
     setup. Yours may be different.

* Usage
 - load up your cports module so that cports can see its own generated
   module files. 
   - the best thing to do is to do a *module initadd dot cports* so
     everytime you login/open a new shell you will have the cports
     environment available to you.
 - To install packages you cd into the
   cports/packages/PACKAGENAME/VERSION that you want, then just type
   *make install*
 - If you want to use a different compiler e.g. do *make install
   COMPILERS=intel* this assumes that you have the intel compilers in
   your path.
** Available COMPILERS
By default COMPILERS=gnu which means it defaults to the system gnu c
compilers (at least version 4 where gfortran is available). This all
assumes that the compilers are already in your path.
*** The default compilers
 - COMPILERS=intel - system version of intel compilers
 - COMPILERS=pathscale - system version of pathscale compilers
 - COMPILERS=pgi - system version of portland compilers
 - COMPILERS=open64 - system version of open64 compilers
*** Accessing to different versions of gnu compilers
For example if you want to vary between the gnu compiler versions
4.1.2, 4.4.0, 4.5.0 etc... you will first need to install the
compilers from the cports system. Then manually load up the
gcc/VERSION compiler with the module utility. To then compile things
you will need to set the COMPILERS variable to hint cports to create
the correct installation directory structures and modulefiles.

Support variables currently available (subject to changes)

  - COMPILERS=open644.2.3
  - COMPILERS=gnu4.5.0
  - COMPILERS=gnu4.4.4
  - COMPILERS=gnu4.4.0

Setting the COMPILERS variable tags things correctly in the
installations. More compilers can be added by editting gnu.local.mk
This method of tagging things isn't straightforward to understand but
it at least provides a way of systematically creating installations.

* Systems tested on
 - ScientificLinux 5.x (64bit)
