Vagrant::Config.run do |config|

  config.vm.define :cports_devel0 do |cports_devel0_config|
    cports_devel0_config.vm.network :hostonly, "192.168.179.254"
    cports_devel0_config.vm.box = "sl63-x86_64"
    cports_devel0_config.vm.customize ["modifyvm", :id, "--memory", 1024]
    cports_devel0_config.vm.host_name = "cports-devel0"
  end

end
